spring:
  application:
    name: Moestilo


  datasource:
    url: jdbc:h2:mem:Moestilo
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    h2:
      console:
        enable: true
        path: /h2-console

    jpa:
      show-sql: true

    flyway:
      enabled: true